name: CI/CD — Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/mydevops-demo:${{ github.sha }}
  SERVICE: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.GCP_REGION }}

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  build-and-deploy:
    name: Build, push image and deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure docker credential helper
        run: |
          gcloud --quiet auth configure-docker

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ secrets.GCP_REGION }}
          allow_unauthenticated: true

      - name: Print service URL
        run: |
          gcloud run services describe "${{ env.SERVICE }}" \
            --project="${{ secrets.GCP_PROJECT }}" \
            --region="${{ secrets.GCP_REGION }}" \
            --format 'value(status.url)'
